logo: İnciBaba TV Üniteleri
title: İnciBaba TV Üniteleri
description: > # this means to ignore newlines until "baseurl:"
  Beğendiğiniz herhangi bir TV ünitesini yapabilirim.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "incibaba.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: "Evinizin Keyfine Varın" # add banner title
banner-desc: "İstediğin herhangi bir tasarımı gönder, TV salonunu güzelleştirelim" # add banner description

# Index settings
showdate: false # set 'false' for hidden date in list of posts

# Author settings
author-pic: face.jpg # your photo
author-name: İhsan Kara (incibaba) # your name
about-author: TV Ünite Dekorasyon Uzmanı # about author
email: 008incibaba@gmail.com # your email
phone: +90 (543)-366-1117 # your pnone number
website: https://incibaba.github.io # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link
whatsapp_url: https://wa.me/905433661117 # add url link

# Disqus
discus_identifier: # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
